# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0002_qsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_password', models.BooleanField(default=False, verbose_name='Change password at next logoi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('institute', models.ForeignKey(blank=True, help_text='Please select the institute for which you intend to publish documents.  If no selection is made, you will be unable to publish.', null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QInstitute')),
                ('projects', models.ManyToManyField(blank=True, to='questionnaire.QProject', verbose_name='Project Membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionnaire User Profile',
                'abstract': False,
                'verbose_name_plural': 'Questionnaire User Profiles',
            },
        ),
    ]
