# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindMapDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
            ],
            options={
                'verbose_name': 'MindMap Domain',
                'verbose_name_plural': 'MindMap Domains',
            },
        ),
        migrations.CreateModel(
            name='MindMapSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MindMap Source',
                'verbose_name_plural': 'MindMap Sources',
            },
        ),
        migrations.AddField(
            model_name='mindmapdomain',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='mindmaps.MindMapSource'),
        ),
    ]
