from Q.questionnaire.signals.signals_ontologies import registered_ontology_handler
from Q.questionnaire.signals.signals_projects import post_save_project_handler, pre_delete_project_handler
from Q.questionnaire.signals.signals_users import post_save_user_handler, post_delete_profile_handler
